version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/mysql:5.7
      - image: circleci/postgres:9.5-alpine-ram
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
          POSTGRES_USER: test
          POSTGRES_DB: spruce_test

    steps:
      - checkout

      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Install MySQL CLI; Import dummy data; run an example query
          command: |
            sudo apt-get install default-mysql-client
            mysql -h localhost -P 3306 -u user -ppassw0rd test_db < ./dummy.sql
            mysql -h localhost -P 3306 -u user -ppassw0rd --execute="SELECT * FROM test_db.Persons"