version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: testpassword

    steps:
      - checkout

      - run: echo "hello!"

      - run: sudo apt-get install mysql-server
      - run: sudo apt-get install mysql-client